--- 
plugins: 
  - 
    feeds: 
      - 
        fresh: false
        name: "WSJ"
        num_stories: 5
        type: "news"
        url: "http://online.wsj.com/xml/rss/3_7011.xml"
      - 
        fresh: false
        name: "NYT"
        num_stories: 5
        type: "news"
        url: "http://feeds.nytimes.com/nyt/rss/HomePage"
      - 
        fresh: true
        name: "HN"
        num_stories: 5
        type: "news"
        url: "http://feeds.feedburner.com/newsyc100"
    name: "DigestRSS"
  - 
    date: "<%= Date.today - 1 %>"
    feed:
     - 
       fresh: false
       name: "NYY"
       url: "http://mlb.mlb.com/partnerxml/gen/news/rss/nyy.xml"
       num_stories: 3
       type: "sports"
    name: "DigestBaseball"
    team: "Yankees"
  - 
    ee_url: "http://evening-edition.com"
    name: "DigestEveningEdition"